Dev
curityio/freja-eid-authenticator pull request #2
Opened 2018-03-30 11:53 UTC by atifsaddique211f

2018-04-10 07:18 UTC, travisspencer requested changes
looks very good. Only changes needed are some polish on the readme.

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +This project provides an opens source Freja eID Authenticator plug-in for the Curity Identity Server. This allows an administrator to add functionality to Curity which will then enable end users to l
> The app that integrates with Curity may also be configured to receive the Freja eID access token and refresh token, allowing it to manage resources in Freja eID.

Can it? It probably shouldn't if so, since Freja doesn't provide any APIs (like Box, Salesforce, etc.) do

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +5. On the next page, you can define all of the standard authenticator configuration options like any previous authenticator that should run, the resulting ACR, transformers that should executed, etc.
`should be executed` instead of `should executed`

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +6. Certain required and optional configuration settings may be provided. One of these required settings is the ``HTTP Client`` setting. This is the HTTP client that will be used to communicate with t
This isn't optional, right, because the mutual TLS is required in all cases (even dev), so a client is needed.

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +    E. Select the ``Client Keystore`` from dropdown, the one you just created in above steps.
```
Select the keystore that you just created in the steps above from the ``Client Keystore`` dropdown.
```

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +5. In order to use ``SSN`` for testing, you need to vet your ID first
maybe just say here, "vet your ID by following the instructions from Verisec." They may chang ethe URL to the vetting portal, and these docs could go stale without us knowing.

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +Note :: You can find detailed instructions from documentation provided by Verisec, the document name will be something like : ``Freja eID Relying Party Documentation - Testing instructions.zip``.
I'd suggest removing
```
, the document name will be something like : ``Freja eID Relying Party Documentation - Testing instructions.zip``
```

2018-04-10 07:18 UTC, travisspencer commented on README.rst
> +Testing Instructions
Some instructions on using the Freja Mock service you made would be helpful.

2018-04-10 07:18 UTC, travisspencer commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/authentication/StartRequestHandler.kt
> +                _logger.error("Got error response from token endpoint: error = {}, {}", statusCode,
I'd log this as a warning.

2018-04-10 07:18 UTC, travisspencer commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/authentication/StartRequestHandler.kt
> +        val data = HashMap<String, Any>(3)
I'd rename this to `dataMap` to be consistent with naming used in a few other places

2018-04-10 07:18 UTC, travisspencer commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/config/FrejaEidAuthenticatorPluginConfig.kt
> +    fun getHost(): String
cool

2018-04-10 07:18 UTC, travisspencer commented on src/main/resources/templates/authenticator/freja-eid/authenticate/wait.vm
> +*  Copyright 2017 Curity AB
was this first created in 2017?

2018-04-10 07:18 UTC, travisspencer commented on src/main/resources/templates/authenticator/freja-eid/authenticate/get.vm
> +*  Copyright 2017 Curity AB
created in 2017?

2018-04-11 07:25 UTC, atifsaddique211f commented on README.rst
> +This project provides an opens source Freja eID Authenticator plug-in for the Curity Identity Server. This allows an administrator to add functionality to Curity which will then enable end users to l
okay, I didn't know, let me remove it.

2018-04-11 07:28 UTC, atifsaddique211f commented on README.rst
> +5. On the next page, you can define all of the standard authenticator configuration options like any previous authenticator that should run, the resulting ACR, transformers that should executed, etc.
okay.

2018-04-11 07:31 UTC, atifsaddique211f commented on README.rst
> +6. Certain required and optional configuration settings may be provided. One of these required settings is the ``HTTP Client`` setting. This is the HTTP client that will be used to communicate with t
yes.

2018-04-11 07:34 UTC, atifsaddique211f commented on README.rst
> +5. In order to use ``SSN`` for testing, you need to vet your ID first
yes.

2018-04-11 07:35 UTC, atifsaddique211f commented on README.rst
> +Note :: You can find detailed instructions from documentation provided by Verisec, the document name will be something like : ``Freja eID Relying Party Documentation - Testing instructions.zip``.
ok

2018-04-11 08:21 UTC, atifsaddique211f commented on README.rst
> +Testing Instructions
okay

2018-04-11 08:26 UTC, atifsaddique211f commented on src/main/resources/templates/authenticator/freja-eid/authenticate/get.vm
> +*  Copyright 2017 Curity AB
no, its a mistake

2018-04-11 08:29 UTC, travisspencer approved these changes

2018-04-11 10:34 UTC, merged