Feature/add backchannel capability
curityio/freja-eid-authenticator pull request #20
Opened 2021-05-03 16:14 UTC by paddy-sr

Added backchannel capability. 
Depends on 6.2.0

2021-05-07 07:51 UTC, travisspencer requested changes

2021-05-07 07:51 UTC, travisspencer commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/authentication/RequestLogicHelper.kt
> +    fun doAuthenticate(postData: Map<String, Any>): Map<String, Any>
please don't use `doXyz` as names. `authenticate` is a verb and makes for a great name

2021-05-07 07:51 UTC, travisspencer commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/authentication/RequestLogicHelper.kt
> +    fun doSign(postData: Map<String, Any>): Map<String, Any>
same comment here

2021-05-07 15:47 UTC, duraisamysathya commented
tested with all the flows. Works as expected

2021-05-17 16:07 UTC, renatoathaydes approved these changes

2021-05-17 16:07 UTC, renatoathaydes commented on src/main/kotlin/io/curity/identityserver/plugin/frejaeid/authentication/FrejaConstants.kt
> +    companion object
You can do `object FrejaConstants` and remove the inner object.

2021-05-19 11:15 UTC, travisspencer approved these changes

2021-05-19 11:16 UTC, merged